// Equivalent to groupid and version in maven, artifactid equivalent is set in settings.gradle.
group 'com.szadowsz'
version '0.1.0'

// IntelliJ is the primary development medium, so it makes sense to add explicit support for it in gradle
apply plugin: 'idea'

    ext {
        scalaVersion = '2.13.17'
        scalaBinaryVersion = '2.13'
        scalaTestVersion = '3.2.20'
        slf4jVersion = '2.0.17'
        junitVersion = '6.0.1'
        seleniumVersion = '4.41.0'
    }


    idea {
	    module {
            downloadJavadoc = true
            downloadSources = true
        }
    }

allprojects {
    repositories {
        mavenCentral()
    }
}

wrapper {
    gradleVersion = '9.4.1'
    distributionType = Wrapper.DistributionType.BIN
}
