// Equivalent to groupid and version in maven, artifactid equivalent is set in settings.gradle.
group 'com.szadowsz'
version '0.1.0'

// IntelliJ is the primary development medium, so it makes sense to add explicit support for it in gradle
apply plugin: 'idea'

// Add necessary language support
apply plugin: 'java'
apply plugin: 'scala'

    ext {
        scalaVersion = '2.13.17'
        scalaBinaryVersion = '2.13'
        scalaTestVersion = '3.2.20'
        slf4jVersion = '2.0.17'
        junitVersion = '6.0.1'
        seleniumVersion = '4.41.0'
    }


    idea {
	    module {
            downloadJavadoc = true
            downloadSources = true
        }
    }

repositories {
    mavenCentral()
    maven {
        url 'http://dl.bintray.com/zakski/default'
        allowInsecureProtocol = true
    }
}


/*
 * Dependencies of the current system. Important dependencies for interops between scala and java are: scala compiler,
 * slf4j logger, scalatest and junit.
 */
dependencies {
    implementation group: 'com.szadowsz', name: 'an-phobail', version: '0.0.1'
    implementation group: 'com.szadowsz', name: 'maeve', version: '0.0.1'
    implementation group: 'org.scala-lang', name: 'scala-library', version: scalaVersion
    implementation group: 'org.slf4j', name: 'slf4j-api', version: slf4jVersion

    testImplementation group: 'org.seleniumhq.selenium', name: 'selenium-chrome-driver', version: seleniumVersion

    testImplementation group: 'org.scalatest', name: "scalatest_${scalaBinaryVersion}", version: scalaTestVersion
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter', version: junitVersion
}

test {
    useJUnitPlatform()
}

wrapper {
    gradleVersion = '9.4.1'
    distributionType = Wrapper.DistributionType.BIN
}
